config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  get '/flights', to: 'flights#index'

  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, :foreign_key => "from_airport_id", class_name: "Flight"
  has_many :arriving_flights, :foreign_key => "to_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, :class_name => "Airport"
  belongs_to :to_airport, :class_name => "Airport"
  has_many :bookings
  has_many :passengers, :through => :bookings

  def self.find_matching_flights(params)
    if params[:search] && ![:date].blank?
      date = params[:date].to_date
      Flight.where(from_airport_id: params[:from],
                   to_airport_id: params[:to],
                   date: date.beginning_of_day..date.end_of_day)
    else
      Flight.none
    end
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
#  has_many :tickets
  has_many :bookings#, :through => :tickets
  has_many :flights, :through => :bookings
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello from the flight booker"
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build

    params[:passengers].to_i.times { @booking.passengers.build }
    @booking.passengers.build if params[:passengers].blank?
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id,
                                      :passengers_attributes => [:name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def new
    @flight = Flight.new
  end

  def index
    @all_airports = Airport.all.map{ |u| [u.city, u.id] }
    @dates = Flight.all.map{ |u| [u.date.strftime("%A, %m/%d/%Y"), u.date.to_date] }.uniq
    @flights = Flight.all
    @passengers = (1..4).map { |u| [u, u]}

    @matching_flights = Flight.find_matching_flights(params)
  end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.erb
<h1>Book Your Flight</h1>

<h2>Flight #<%= @flight.id+200 %></h2>

<h3><%= @flight.from_airport.city %> To <%= @flight.to_airport.city %></h3>

<p>Flight Date: <%= @flight.date.strftime("%A, %m/%d/%Y at %H:%M %p") %></p>

<%= form_for(@booking) do |f| %>
  <%= f.hidden_field :flight_id %>
  <%= f.fields_for :passengers do |passenger| %>
    <%= passenger.label :name %>
    <%= passenger.text_field :name %>

    <%= passenger.label :email %>
    <%= passenger.text_field :email %>
  <% end %>

  <%= f.submit "Book Flight", class: "button" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>

<p>Your flight has been booked.</p>
<p>Flight <%= @booking.flight.id+200 %>, <%= @booking.flight.from_airport.airport_code %> to <%= @booking.flight.to_airport.airport_code %></p>
<p>Your flight is scheduled for <%= @booking.flight.date.strftime("%A, %m/%d/%Y at %H:%M %p") %> </p>
<p>Please arrive at least 2 hours early to make sure TSA has a chance to screw up!</p>

<h3>Passengers:</h3>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li> <%= "#{passenger.name}, #{passenger.email}" %></li>
  <% end %>
</ol>

app/views/flights/index.html.erb
<h1>Flights</h1>
<%= form_tag flights_path, method: 'GET' do %>
  <%= hidden_field_tag :search %>
  <%= select_tag :from, options_for_select(@all_airports), prompt: "From" %>
  <%= select_tag :to, options_for_select(@all_airports), prompt: "To" %>
  <%= select_tag :date, options_for_select(@dates), prompt: "Date" %>
  <%= select_tag :passengers, options_for_select(@passengers), prompt: "Passengers" %>
  <%= submit_tag "Search", :name => nil, class: "button" %>

<% end %>

<% if @matching_flights.any? %>
  <h1>Available Flights</h1>
  <%= form_tag new_booking_path, method: 'GET' do %>
    <% @matching_flights.each do |e| %>
      <p>
        <%= radio_button_tag :flight_id, e.id %>
        From: <%= e.from_airport.city %>
        To: <%= e.to_airport.city %>
        Date: <%= e.date.strftime("%A, %m/%d/%Y at %H:%M %p") %>
        Duration: <%= distance_of_time_in_words(e.duration) %>
        <%= submit_tag "Choose Flight", :name => nil, class: "button" %>
        <%= hidden_field_tag :passengers, params[:passengers] %>
      </p>
    <% end %>
  <% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>